<h3>LIBRERIAS</h3>

In [1]:
import pandas as pd
from pathlib import Path

<h3>CARGAR</h3>

In [2]:
ruta_parquet = Path(r"../1. Datasets/1. Dataset Original")

df_mht = pd.read_csv(ruta_parquet/"mental_health_trends.csv")

<h3>DIAGNOSTICO Y LIMPIEZA - METAL HEALTH TRENDS</h3>

In [3]:
# ENCABEZADO
df_mht.head()

,user_id,year,country,age_group,gender,platform,anxiety_score,depression_score,stress_level,loneliness_index,therapy_access,medication_usage,self_esteem_score,mental_health_risk
0,23655,2014,Saudi Arabia,Adult,Female,X/Twitter,61.24,33.50,66.03,66.49,True,False,38.66,Medium
1,15796,2011,Spain,Young Adult,Male,X/Twitter,67.80,47.65,72.91,48.61,False,True,61.53,High
2,861,2035,Brazil,Senior,Other,Instagram,79.80,88.73,68.16,49.53,False,True,53.75,Medium
3,5391,2034,USA,Young Adult,Male,Reddit,49.41,48.83,51.07,66.71,True,False,60.80,Medium
4,21576,2059,Mexico,Young Adult,Other,Twitch,84.60,70.59,50.64,51.14,True,False,61.16,High

In [4]:
# ANALISIS DESCRIPTIVO
df_mht.describe()

,user_id,year,anxiety_score,depression_score,stress_level,loneliness_index,self_esteem_score
count,50000.000000,50000.00000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000
mean,12543.006140,2035.01650,54.936583,49.944387,59.93562,48.071525,51.901217
std,7198.845434,14.67521,17.878522,19.747969,14.96799,16.985095,15.951184
min,1.000000,2010.00000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,6326.750000,2022.00000,42.920000,36.460000,49.85000,36.510000,41.100000
50%,12567.500000,2035.00000,55.080000,49.880000,59.88000,48.175000,51.930000
75%,18750.000000,2048.00000,67.140000,63.370000,70.03000,59.580000,62.730000
max,25000.000000,2060.00000,100.000000,100.000000,100.00000,100.000000,100.000000

In [5]:
# INFORMACIÓN
df_mht.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             50000 non-null  int64
 1   year                50000 non-null  int64
 2   country             50000 non-null  object
 3   age_group           50000 non-null  object
 4   gender              50000 non-null  object
 5   platform            50000 non-null  object
 6   anxiety_score       50000 non-null  float64
 7   depression_score    50000 non-null  float64
 8   stress_level        50000 non-null  float64
 9   loneliness_index    50000 non-null  float64
 10  therapy_access      50000 non-null  bool
 11  medication_usage    50000 non-null  bool
 12  self_esteem_score   50000 non-null  float64
 13  mental_health_risk  50000 non-null  object
dtypes: bool(2), float64(5), int64(2), object(5)
memory usage: 4.7+ MB

In [6]:
# VERIFICACIÓN DE NULOS
df_mht.isnull().sum()

user_id               0
year                  0
country               0
age_group             0
gender                0
platform              0
anxiety_score         0
depression_score      0
stress_level          0
loneliness_index      0
therapy_access        0
medication_usage      0
self_esteem_score     0
mental_health_risk    0
dtype: int64

In [7]:
# RANGO AÑO 
print("Min:", df_mht['year'].min(), "| Max:", df_mht['year'].max())

Min: 2010 | Max: 2060

In [8]:
# CONVERTIR USER_ID EN STRING
df_mht['user_id'] = df_mht['user_id'].astype(str)

In [9]:
# CAMBIAR NOMBRE DE COLUMNAS

df_mht.rename(columns={
    'user_id'           : 'id_usuario',
    'year'              : 'anio',
    'country'           : 'pais',
    'age_group'         : 'grupo_edad',
    'gender'            : 'genero',
    'platform'          : 'plataforma',
    'anxiety_score'     : 'puntaje_ansiedad',
    'depression_score'  : 'puntaje_depresion',
    'stress_level'      : 'nivel_estres',
    'loneliness_index'  : 'indice_soledad',
    'therapy_access'    : 'acceso_terapia',
    'medication_usage'  : 'uso_medicacion',
    'self_esteem_score' : 'puntaje_autoestima',
    'mental_health_risk': 'riesgo_salud_mental'
}, inplace=True)

In [10]:
# VERIFICACIÓN
df_mht.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_usuario           50000 non-null  object
 1   anio                 50000 non-null  int64
 2   pais                 50000 non-null  object
 3   grupo_edad           50000 non-null  object
 4   genero               50000 non-null  object
 5   plataforma           50000 non-null  object
 6   puntaje_ansiedad     50000 non-null  float64
 7   puntaje_depresion    50000 non-null  float64
 8   nivel_estres         50000 non-null  float64
 9   indice_soledad       50000 non-null  float64
 10  acceso_terapia       50000 non-null  bool
 11  uso_medicacion       50000 non-null  bool
 12  puntaje_autoestima   50000 non-null  float64
 13  riesgo_salud_mental  50000 non-null  object
dtypes: bool(2), float64(5), int64(1), object(6)
memory usage: 4.7+ MB

<h3>AGREGACIÓN DE NUEVOS ATRIBUTOS</h3>

In [11]:
# INDICE BIENESTAR DIGITAL
df_mht['indice_bienestar_digital'] = 100 - ((df_mht['puntaje_ansiedad'] + df_mht['puntaje_depresion'] + df_mht['nivel_estres']) / 3).round(2)

# Resume en un solo número el estado psicologico del paciente. Valor alto equivale a mejor bienestar. 

# BRECHA DE AUTOESTIMA ANSIEDAD
df_mht['brecha_autoestima_ansiedad'] = (df_mht['puntaje_autoestima'] - df_mht['puntaje_ansiedad']).round(2)

# Una baja autoestima combinada con una alta ansiedad es un patron de riesgo, valores negativos indican que la ansiedad supera el autoestima. 

# APOYO CLINICO
df_mht['apoyo_clinico'] = (df_mht['acceso_terapia'].astype(int) + df_mht['uso_medicacion'].astype(int))
# 0 = sin apoyo, 1 = apoyo parcial, 2 = apoyo completo

# RIESGO ORDEN
orden = {'Low': 1, 'Medium': 2, 'High': 3}
df_mht['riesgo_orden'] = df_mht['riesgo_salud_mental'].map(orden)

In [12]:
df_mht

,id_usuario,anio,pais,grupo_edad,genero,plataforma,puntaje_ansiedad,puntaje_depresion,nivel_estres,indice_soledad,acceso_terapia,uso_medicacion,puntaje_autoestima,riesgo_salud_mental,indice_bienestar_digital,brecha_autoestima_ansiedad,apoyo_clinico,riesgo_orden
0,23655,2014,Saudi Arabia,Adult,Female,X/Twitter,61.24,33.50,66.03,66.49,True,False,38.66,Medium,46.41,-22.58,1,2
1,15796,2011,Spain,Young Adult,Male,X/Twitter,67.80,47.65,72.91,48.61,False,True,61.53,High,37.21,-6.27,1,3
2,861,2035,Brazil,Senior,Other,Instagram,79.80,88.73,68.16,49.53,False,True,53.75,Medium,21.10,-26.05,1,2
3,5391,2034,USA,Young Adult,Male,Reddit,49.41,48.83,51.07,66.71,True,False,60.80,Medium,50.23,11.39,1,2
4,21576,2059,Mexico,Young Adult,Other,Twitch,84.60,70.59,50.64,51.14,True,False,61.16,High,31.39,-23.44,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,19937,2049,South Korea,Teen,Other,YouTube,82.75,23.74,86.86,46.05,True,False,34.27,Low,35.55,-48.48,1,1
49996,15384,2013,Saudi Arabia,Children,Other,Instagram,62.90,80.33,62.09,40.40,True,False,24.28,High,31.56,-38.62,1,3
49997,19540,2041,Brazil,Adult,Male,Discord,65.05,39.83,71.30,70.65,False,False,27.86,Low,41.27,-37.19,0,1
49998,16672,2045,South Korea,Adult,Other,Reddit,22.54,42.08,38.29,68.97,False,True,41.17,Low,65.70,18.63,1,1
49999,20090,2013,Spain,Adult,Male,Reddit,56.17,12.45,74.28,75.59,True,False,70.10,High,52.37,13.93,1,3

In [ ]:
# RUTA DONDE SE GUARDARÁN LOS PARQUET
ruta_limpio = Path(r"../1. Datasets/2. Dataset Limpio")

# EXPORTAR CADA DATASET COMO PARQUET
df_mht.to_parquet(ruta_limpio/"mental_health_trends.parquet", index=False)

# EXPORTAR CADA DATASET COMO CSV
df_mht.to_csv(ruta_limpio/"mental_health_trends.csv", index=False)