<h3>LIBRERIAS</h3>

In [ ]:
import pandas as pd
from pathlib import Path

<h3>CARGAR</h3>

In [ ]:
ruta_parquet = Path(r"../1. Datasets/1. Dataset Original")

df_smu = pd.read_csv(ruta_parquet/"social_media_usage.csv")

<h3>DIAGNOSTICO Y LIMPIEZA - SOCIAL MEDIA USAGE</h3>

In [ ]:
# ENCABEZADO
df_smu.head()

,user_id,year,country,age_group,gender,platform,daily_screen_time_hours,doomscrolling_frequency,notification_checks_per_day,ai_recommendation_exposure,productivity_loss_pct,digital_detox_attempts,addiction_risk_level
0,7857,2036,UK,Senior,Female,Facebook,6.10,9.69,333,86.08,32.66,11,Low
1,21853,2060,Italy,Senior,Other,YouTube,7.61,4.22,246,76.60,24.24,6,Low
2,8524,2060,USA,Children,Female,YouTube,9.01,6.16,107,6.23,69.08,14,High
3,12728,2049,China,Children,Male,Twitch,3.98,5.61,214,27.73,20.08,2,Medium
4,14938,2058,Australia,Senior,Male,Snapchat,4.06,9.43,111,37.88,64.55,6,Low

In [ ]:
# ANALISIS DESCRIPTIVO
df_smu.describe()

,user_id,year,daily_screen_time_hours,doomscrolling_frequency,notification_checks_per_day,ai_recommendation_exposure,productivity_loss_pct,digital_detox_attempts
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,12482.723880,2035.132420,5.995321,5.017518,177.297700,50.196940,35.101957,6.982880
std,7216.241558,14.723408,1.990299,2.883153,99.651905,28.919281,20.173603,4.323679
min,1.000000,2010.000000,0.500000,0.000000,5.000000,0.000000,0.000000,0.000000
25%,6245.000000,2022.000000,4.650000,2.530000,91.000000,25.100000,17.610000,3.000000
50%,12410.000000,2035.000000,5.990000,5.030000,178.000000,50.190000,35.230000,7.000000
75%,18771.000000,2048.000000,7.340000,7.520000,264.000000,75.232500,52.632500,11.000000
max,25000.000000,2060.000000,14.660000,10.000000,349.000000,100.000000,69.990000,14.000000

In [ ]:
# INFORMACIÓN
df_smu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   user_id                      50000 non-null  int64
 1   year                         50000 non-null  int64
 2   country                      50000 non-null  object
 3   age_group                    50000 non-null  object
 4   gender                       50000 non-null  object
 5   platform                     50000 non-null  object
 6   daily_screen_time_hours      50000 non-null  float64
 7   doomscrolling_frequency      50000 non-null  float64
 8   notification_checks_per_day  50000 non-null  int64
 9   ai_recommendation_exposure   50000 non-null  float64
 10  productivity_loss_pct        50000 non-null  float64
 11  digital_detox_attempts       50000 non-null  int64
 12  addiction_risk_level         50000 non-null  object
dtypes: float64(4), int64(4), object(5)
memory usage: 5.0+ MB

In [ ]:
# VERIFICACIÓN DE NULOS
df_smu.isnull().sum()

user_id                        0
year                           0
country                        0
age_group                      0
gender                         0
platform                       0
daily_screen_time_hours        0
doomscrolling_frequency        0
notification_checks_per_day    0
ai_recommendation_exposure     0
productivity_loss_pct          0
digital_detox_attempts         0
addiction_risk_level           0
dtype: int64

In [ ]:
# RANGO AÑO 
print("Min:", df_smu['year'].min(), "| Max:", df_smu['year'].max())

Min: 2010 | Max: 2060

In [ ]:
# CONVERTIR USER_ID EN STRING
df_smu['user_id'] = df_smu['user_id'].astype(str)

# ELIMINAR COLUMNAS 
df_smu.drop(columns=['notification_checks_per_day', 'digital_detox_attempts'], inplace=True)

In [ ]:
# CAMBIAR NOMBRE DE COLUMNAS
df_smu.rename(columns={
    'user_id'                    : 'id_usuario',
    'year'                       : 'anio',
    'country'                    : 'pais',
    'age_group'                  : 'grupo_edad',
    'gender'                     : 'genero',
    'platform'                   : 'plataforma',
    'daily_screen_time_hours'    : 'horas_pantalla_diaria',
    'doomscrolling_frequency'    : 'frecuencia_doomscrolling',
    'ai_recommendation_exposure' : 'exposicion_recomendacion_ia',
    'productivity_loss_pct'      : 'pct_perdida_productividad',
    'addiction_risk_level'       : 'nivel_riesgo_adiccion'
}, inplace=True)

In [ ]:
# VERIFICACIÓN
df_smu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id_usuario                   50000 non-null  object
 1   anio                         50000 non-null  int64
 2   pais                         50000 non-null  object
 3   grupo_edad                   50000 non-null  object
 4   genero                       50000 non-null  object
 5   plataforma                   50000 non-null  object
 6   horas_pantalla_diaria        50000 non-null  float64
 7   frecuencia_doomscrolling     50000 non-null  float64
 8   exposicion_recomendacion_ia  50000 non-null  float64
 9   pct_perdida_productividad    50000 non-null  float64
 10  nivel_riesgo_adiccion        50000 non-null  object
dtypes: float64(4), int64(1), object(6)
memory usage: 4.2+ MB

<h3>AGREGACIÓN DE NUEVOS ATRIBUTOS</h3>

In [ ]:
# USO DE PANTALLA CATEGORIA
bins = [0, 3, 6, 9, 15]
labels = ['Bajo', 'Moderado', 'Alto', 'Severo']
df_smu['uso_pantalla_categoria'] = pd.cut(df_smu['horas_pantalla_diaria'], bins=bins, labels=labels)

# Categoriza las horas de pantalla en niveles clínicos. En medicina digital se considera uso problemático a partir de 6 horas diarias.

# DOOMSCROLLING CATEGORIA
bins = [0, 3, 6, 10]
labels = ['Leve', 'Moderado', 'Severo']
df_smu['doomscrolling_categoria'] = pd.cut(df_smu['frecuencia_doomscrolling'], bins=bins, labels=labels, include_lowest=True)

#Segmenta el doomscrolling en niveles.

In [ ]:
df_smu

,id_usuario,anio,pais,grupo_edad,genero,plataforma,horas_pantalla_diaria,frecuencia_doomscrolling,exposicion_recomendacion_ia,pct_perdida_productividad,nivel_riesgo_adiccion,uso_pantalla_categoria,doomscrolling_categoria
0,7857,2036,UK,Senior,Female,Facebook,6.10,9.69,86.08,32.66,Low,Alto,Severo
1,21853,2060,Italy,Senior,Other,YouTube,7.61,4.22,76.60,24.24,Low,Alto,Moderado
2,8524,2060,USA,Children,Female,YouTube,9.01,6.16,6.23,69.08,High,Severo,Severo
3,12728,2049,China,Children,Male,Twitch,3.98,5.61,27.73,20.08,Medium,Moderado,Moderado
4,14938,2058,Australia,Senior,Male,Snapchat,4.06,9.43,37.88,64.55,Low,Moderado,Severo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20080,2011,UAE,Teen,Male,Twitch,5.00,5.47,19.64,54.27,Low,Moderado,Moderado
49996,13130,2051,South Korea,Senior,Female,Reddit,4.89,1.76,1.25,44.41,High,Moderado,Leve
49997,24140,2046,Italy,Children,Other,Instagram,3.39,1.59,29.92,43.68,Medium,Moderado,Leve
49998,15190,2060,UK,Teen,Female,X/Twitter,7.76,0.27,63.85,52.92,Medium,Alto,Leve
49999,2433,2055,India,Adult,Male,Twitch,4.43,5.07,86.47,49.35,Medium,Moderado,Moderado

In [ ]:
# RUTA DONDE SE GUARDARÁN LOS PARQUET
ruta_limpio = Path(r"../1. Datasets/2. Dataset Limpio")

# EXPORTAR CADA DATASET COMO PARQUET
#df_smu.to_parquet(ruta_limpio/"social_media_usage.parquet", index=False)

# EXPORTAR CADA DATASET COMO CSV
df_dtm.to_csv(ruta_limpio/"social_media_usage.csv", index=False)